# Generated by Django 5.2.8 on 2025-11-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crimereport",
            old_name="reporter",
            new_name="reported_by",
        ),
        migrations.AddField(
            model_name="crimereport",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crimereport",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crimereport",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="crimereport",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
