# Generated by Django 5.2.8 on 2025-11-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_reporter_crimereport_reported_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crimereport",
            old_name="reported_by",
            new_name="reporter",
        ),
        migrations.AlterField(
            model_name="crimereport",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="crimereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("investigating", "Investigating"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="crimereport",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
