# Generated by Django 5.2.8 on 2025-11-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_reported_by_crimereport_reporter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crimereport",
            name="evidence",
            field=models.FileField(blank=True, null=True, upload_to="evidence/"),
        ),
    ]
