# Generated by Django 5.2.8 on 2025-11-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_crimereport_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="crimereport",
            name="crime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="crimereport",
            name="priority",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="crimereport",
            name="severity",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="crimereport",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
