# Generated by Django 5.2.8 on 2025-11-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_crimereport_crime_type_crimereport_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crimereport",
            name="llm_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
