# Generated by Django 5.2.8 on 2025-11-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_crimereport_llm_confidence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("citizen", "Citizen"),
                    ("police", "Police"),
                    ("admin", "Admin"),
                ],
                default="citizen",
                max_length=20,
            ),
        ),
    ]
