# Generated by Django 5.2.8 on 2025-11-13 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_user_full_name_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="crimereport",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
