# Generated by Django 5.2.8 on 2025-11-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_crimereport_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="crimereport",
            name="ipc_sections",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crimereport",
            name="llm_raw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crimereport",
            name="recommended_action",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crimereport",
            name="severity_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
