# Generated by Django 5.2.8 on 2025-11-13 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_crimereport_ipc_sections_crimereport_llm_raw_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crimereport",
            name="ipc_sections",
        ),
        migrations.RemoveField(
            model_name="crimereport",
            name="llm_raw",
        ),
        migrations.RemoveField(
            model_name="crimereport",
            name="recommended_action",
        ),
        migrations.RemoveField(
            model_name="crimereport",
            name="severity_score",
        ),
    ]
