# Generated by Django 5.2.8 on 2025-11-13 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_remove_crimereport_ipc_sections_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create_report", "Create Report"),
                            ("update_status", "Update Status"),
                            ("assign_report", "Assign Report"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("delete_report", "Delete Report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
